### ISSUE TITLE
Open to suggestions / contributions?

### ISSUE THREAD

**Issue by austriker27** [Smithbm2316/synthwave-everything#1]
Hello,

I also love synthwav-ing everything... Are you open to suggestions or contributions? 

Example: I use Hyper for my terminal and have installed some stuff to make it very synthwave.

**Comment by smithbm2316** [comment]
Yes I am! If you have suggestions, I'd love to hear them. Please open a pull request and I’d be happy to add your hyper theming to the repo 😃
